# Generated by Django 5.1.3 on 2024-12-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=64)),
                ('title', models.CharField(default='', max_length=64)),
                ('url', models.URLField()),
                ('directions', models.TextField()),
                ('reviews', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('dislikes', models.ManyToManyField(related_name='disliked_users', to='api.recipe')),
                ('likes', models.ManyToManyField(related_name='liked_users', to='api.recipe')),
            ],
        ),
    ]
